Debug Qt5 location #trigger_ci

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -3,60 +3,60 @@ addons:
   ssh_known_hosts: gulinux.net:8122
 matrix:
     include:
-        - language: cpp
-          env:
-            - QT5_BASEDIR: "C:/Qt"
-            - QT5_DIR: "C:/Qt/${QT5_VERSION}/msvc2019_64"
-            - PATH: /c/Python38:/c/Python38/Scripts:$PATH
-          name: AstroPhoto Plus Desktop - Windows
-          os: windows
-          cache:
-            directories:
-            - C:/Qt
-          install:
-            - bash ${TRAVIS_BUILD_DIR}/support/travis-qt-installer
-            - cinst -y visualstudio2019-workload-netcorebuildtools visualstudio2019-workload-vctools visualstudio2019-workload-webbuildtools visualstudio2019buildtools
-          before_script:
-            - mkdir ${TRAVIS_BUILD_DIR}/build
-            - find "$QT5_BASEDIR" -type f
-            - $QT5_DIR/bin/qtenv2.bat
-          script:
-            - cd ${TRAVIS_BUILD_DIR}/build
-            - if ! cmake ${TRAVIS_BUILD_DIR} -DCMAKE_PREFIX_PATH=${QT5_DIR} -DQt5_DIR=${QT5_DIR} -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=$PWD/pkg; then
-                  cat ${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log;
-                  exit 1;
-              fi
-            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release 
-          after_success:
-            - export TRAVIS_WINDOWS_BUILD_DIR="$( cd "${TRAVIS_BUILD_DIR}"; pwd -W)"
-            - cd ${TRAVIS_BUILD_DIR}/build
-            - cinst -y python3
-            - cinst -y nsis
-            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release --target install
-            - $QT5_DIR/bin/windeployqt --dir $TRAVIS_BUILD_DIR/build/pkg/bin $TRAVIS_BUILD_DIR/build/pkg/bin/AstroPhotoPlus-Desktop.exe  --release --no-compiler-runtime
-            - cd "$TRAVIS_BUILD_DIR/build/pkg/bin"
-            - |
-                "C:/Program Files (x86)/NSIS/makensis.exe" //NOCD ${TRAVIS_BUILD_DIR}/src/resources/installer.nsis
-            - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
-            - echo ${PROJECT_VERSION}
-            - echo ${TRAVIS_WINDOWS_BUILD_DIR}
-            - export VERSION=${PROJECT_VERSION}
-            - cd ${TRAVIS_BUILD_DIR}/build
-            - pwd
-            - wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/a68a8df028a02ce2730720b9aec8c77f5ada7496/python/travis_release.py"
-            - ls -alh ${TRAVIS_BUILD_DIR}/build/travis_release.py
-            - md5sum travis_release.py
-            - pip install PyGithub
-            - mv -v "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Setup.exe" "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Windows-Setup.exe"
-
-          deploy:
-            skip_cleanup: true
-            provider: script
-            script: python ${TRAVIS_WINDOWS_BUILD_DIR}/build/travis_release.py "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Windows-Setup.exe"
-            on:
-              branch:
-                - master
-              tags: false
+#        - language: cpp
+#          env:
+#            - QT5_BASEDIR: "C:/Qt"
+#            - QT5_DIR: "C:/Qt/${QT5_VERSION}/msvc2019_64"
+#            - PATH: /c/Python38:/c/Python38/Scripts:$PATH
+#          name: AstroPhoto Plus Desktop - Windows
+#          os: windows
+#          cache:
+#            directories:
+#            - C:/Qt
+#          install:
+#            - bash ${TRAVIS_BUILD_DIR}/support/travis-qt-installer
+#            - cinst -y visualstudio2019-workload-netcorebuildtools visualstudio2019-workload-vctools visualstudio2019-workload-webbuildtools visualstudio2019buildtools
+#          before_script:
+#            - mkdir ${TRAVIS_BUILD_DIR}/build
+#            - find "$QT5_BASEDIR" -type f
+#            - $QT5_DIR/bin/qtenv2.bat
+#          script:
+#            - cd ${TRAVIS_BUILD_DIR}/build
+#            - if ! cmake ${TRAVIS_BUILD_DIR} -DCMAKE_PREFIX_PATH=${QT5_DIR} -DQt5_DIR=${QT5_DIR} -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=$PWD/pkg; then
+#                  cat ${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log;
+#                  exit 1;
+#              fi
+#            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release 
+#          after_success:
+#            - export TRAVIS_WINDOWS_BUILD_DIR="$( cd "${TRAVIS_BUILD_DIR}"; pwd -W)"
+#            - cd ${TRAVIS_BUILD_DIR}/build
+#            - cinst -y python3
+#            - cinst -y nsis
+#            - cmake --build ${TRAVIS_BUILD_DIR}/build --parallel --config Release --target install
+#            - $QT5_DIR/bin/windeployqt --dir $TRAVIS_BUILD_DIR/build/pkg/bin $TRAVIS_BUILD_DIR/build/pkg/bin/AstroPhotoPlus-Desktop.exe  --release --no-compiler-runtime
+#            - cd "$TRAVIS_BUILD_DIR/build/pkg/bin"
+#            - |
+#                "C:/Program Files (x86)/NSIS/makensis.exe" //NOCD ${TRAVIS_BUILD_DIR}/src/resources/installer.nsis
+#            - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
+#            - echo ${PROJECT_VERSION}
+#            - echo ${TRAVIS_WINDOWS_BUILD_DIR}
+#            - export VERSION=${PROJECT_VERSION}
+#            - cd ${TRAVIS_BUILD_DIR}/build
+#            - pwd
+#            - wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/a68a8df028a02ce2730720b9aec8c77f5ada7496/python/travis_release.py"
+#            - ls -alh ${TRAVIS_BUILD_DIR}/build/travis_release.py
+#            - md5sum travis_release.py
+#            - pip install PyGithub
+#            - mv -v "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Setup.exe" "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Windows-Setup.exe"
+#
+#          deploy:
+#            skip_cleanup: true
+#            provider: script
+#            script: python ${TRAVIS_WINDOWS_BUILD_DIR}/build/travis_release.py "${TRAVIS_WINDOWS_BUILD_DIR}/build/pkg/bin/AstroPhoto-Plus-Desktop-Windows-Setup.exe"
+#            on:
+#              branch:
+#                - master
+#              tags: false
 
 
         - language: cpp
@@ -74,6 +74,7 @@ matrix:
               - sudo apt-get -qq -y install libgl1-mesa-dev wget libfontconfig1 libxrender1  libdbus-1-3 libxkbcommon0 libxkbcommon-x11-0 xvfb libpulse-dev p7zip-full python3-requests
               - sudo apt-get -qq -y install libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-present0 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxcb1
               - python3 ${TRAVIS_BUILD_DIR}/support/qt-installer.py "${QT5_DIR}"
+              - ls -alh "${QT5_DIR}"
           before_script:
               - mkdir ${TRAVIS_BUILD_DIR}/build
               - cd ${TRAVIS_BUILD_DIR}/build
@@ -110,41 +111,41 @@ matrix:
                 - master
               tags: false
 
-        - language: cpp
-          name: Astrophoto Plus Desktop - Mac Os App
-          os: osx
-          env:
-            - QT5_BASEDIR: "$HOME/Qt"
-            - QT5_DIR: "$HOME/Qt/${QT5_VERSION}/clang_64"
-          install:
-            - bash ${TRAVIS_BUILD_DIR}/support/travis-qt-installer
-          before_script:
-              - mkdir ${TRAVIS_BUILD_DIR}/build
-              - cd ${TRAVIS_BUILD_DIR}/build
-          script:
-              - cd ${TRAVIS_BUILD_DIR}/build
-              - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release -DQt5_DIR=${QT5_DIR}/lib/cmake/Qt5/
-              - make -j$(nproc)
-              - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
-              - make install -j$(nproc) DESTDIR=${TRAVIS_BUILD_DIR}/build/appdir
-          after_success:
-              - cd "${TRAVIS_BUILD_DIR}/build"
-              - echo ${PROJECT_VERSION}
-              - export VERSION=${PROJECT_VERSION}
-              - ${QT5_DIR}/bin/macdeployqt appdir/AstroPhotoPlus-Desktop.app -dmg -verbose 3
-              - wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/a68a8df028a02ce2730720b9aec8c77f5ada7496/python/travis_release.py"
-              - ls -alh ${TRAVIS_BUILD_DIR}/build
-              - md5sum travis_release.py
-              - python3 -m venv ${TRAVIS_BUILD_DIR}/build/venv
-              - source ${TRAVIS_BUILD_DIR}/build/venv/bin/activate
-              - pip3 install PyGithub
-              - mv -v "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop.dmg" "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop-OSX.dmg"
-          deploy:
-            skip_cleanup: true
-            provider: script
-            script: python3 "${TRAVIS_BUILD_DIR}/build/travis_release.py" "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop-OSX.dmg"
-            on:
-              branch:
-                - master
-              tags: false
+#        - language: cpp
+#          name: Astrophoto Plus Desktop - Mac Os App
+#          os: osx
+#          env:
+#            - QT5_BASEDIR: "$HOME/Qt"
+#            - QT5_DIR: "$HOME/Qt/${QT5_VERSION}/clang_64"
+#          install:
+#            - bash ${TRAVIS_BUILD_DIR}/support/travis-qt-installer
+#          before_script:
+#              - mkdir ${TRAVIS_BUILD_DIR}/build
+#              - cd ${TRAVIS_BUILD_DIR}/build
+#          script:
+#              - cd ${TRAVIS_BUILD_DIR}/build
+#              - cmake ${TRAVIS_BUILD_DIR} -DCMAKE_BUILD_TYPE=Release -DQt5_DIR=${QT5_DIR}/lib/cmake/Qt5/
+#              - make -j$(nproc)
+#              - source ${TRAVIS_BUILD_DIR}/build/src/resources/version.env
+#              - make install -j$(nproc) DESTDIR=${TRAVIS_BUILD_DIR}/build/appdir
+#          after_success:
+#              - cd "${TRAVIS_BUILD_DIR}/build"
+#              - echo ${PROJECT_VERSION}
+#              - export VERSION=${PROJECT_VERSION}
+#              - ${QT5_DIR}/bin/macdeployqt appdir/AstroPhotoPlus-Desktop.app -dmg -verbose 3
+#              - wget --quiet "https://raw.githubusercontent.com/GuLinux/GuLinux-Commons/a68a8df028a02ce2730720b9aec8c77f5ada7496/python/travis_release.py"
+#              - ls -alh ${TRAVIS_BUILD_DIR}/build
+#              - md5sum travis_release.py
+#              - python3 -m venv ${TRAVIS_BUILD_DIR}/build/venv
+#              - source ${TRAVIS_BUILD_DIR}/build/venv/bin/activate
+#              - pip3 install PyGithub
+#              - mv -v "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop.dmg" "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop-OSX.dmg"
+#          deploy:
+#            skip_cleanup: true
+#            provider: script
+#            script: python3 "${TRAVIS_BUILD_DIR}/build/travis_release.py" "${TRAVIS_BUILD_DIR}/build/appdir/AstroPhotoPlus-Desktop-OSX.dmg"
+#            on:
+#              branch:
+#                - master
+#              tags: false
 
